log4j.rootLogger=INFO, logfile
log4j.logger.com.easysoft=INFO
log4j.logger.org.hibernate.SQL=INFO

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %p [%c] - <%m>%n

# If you running mvn jetty:run in an ANSI console (bash, rxvt), then use A1 instead of stdout
log4j.appender.A1=org.apache.log4j.ConsoleAppender
log4j.appender.A1.layout=com.easysoft.ecommerce.service.impl.ANSIColorLayout
log4j.appender.A1.layout.ConversionPattern=%d %p [%c] - <%m>%n

# LOG FILE
log4j.appender.logfile=org.apache.log4j.RollingFileAppender
log4j.appender.logfile.File=/tmp/ecommerce.log
log4j.appender.logfile.MaxFileSize=5MB
log4j.appender.logfile.MaxBackupIndex=30
log4j.appender.logfile.layout=org.apache.log4j.PatternLayout
log4j.appender.logfile.layout.ConversionPattern=%d %p [%c] - <%m>%n