#Style
styleSheet=/wro/{0}pink_css.css

javascript=/wro/{0}pink_js.js

#buttons
global.search.button=/themes/pink/images/common/buttons/but-header-search.gif
refinement.plus.button=/themes/pink/images/common/buttons/but-square-plus-sign.gif
refinement.minus.button=/themes/pink/images/common/buttons/but-square-minus-sign.gif

#background
background=
