# Default values for locale, timezone and theme name
defaultLocale=en_US
defaultTimeZone=America/New_York
defaultTheme=default

messageBundle=messages

# file system (FileSystemService) config
workingDir=/usr/local/ecommerceWorkingDir
