# Default values for locale, timezone and theme name
defaultLocale=vi_VN
defaultTimeZone=GMT+7
defaultTheme=default

messageBundle=messages

# file system (FileSystemService) config
workingDir=/usr/local/ecommerceWorkingDir
